sudo: required

services:
- docker

before_install:
- VERSION=v1.11.x-7.4-redhat
- CENTOS_VERSION=7.4.1708
- DOCKER_VERSION=1.13.1-75.git8633870.el7.centos.x86_64
- KUBERNETES_VERSION=v1.11.6

script:
- >
   docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo centos:${CENTOS_VERSION}
   bash -c
   "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
      yum install -y https://download.ceph.com/rpm-luminous/el7/noarch/ceph-release-1-1.el7.noarch.rpm &&
      mkdir -p /rpms &&
      yum remove -y python-chardet &&
      yum -y install --downloadonly --downloaddir=/rpms yum-utils device-mapper-persistent-data lvm2 &&
      yum -y install --downloadonly --downloaddir=/rpms docker-${DOCKER_VERSION} docker-python docker-compose python-chardet python-requests python-jinja2 &&
      yum -y install --downloadonly --downloaddir=/rpms ipset ipvsadm conntrack-tools &&
      yum -y install --downloadonly --downloaddir=/rpms audit rsync jq git tcpdump nc bind-utils net-tools chrony &&
      yum -y install --downloadonly --downloaddir=/rpms ceph-deploy ceph ceph-radosgw rbd-nbd rbd-mirror open-vm-tools  nfs-utils && 
      yum -y install --downloadonly --downloaddir=/rpms kubernetes-cni-0.6.0 kubectl-${KUBERNETES_VERSION:1} kubelet-${KUBERNETES_VERSION:1} kubeadm-${KUBERNETES_VERSION:1} &&
      yum install -y createrepo &&
      yum clean all && createrepo /rpms"
- sudo chmod -R 755 ${PWD}/rpms
- docker build -t wisecloud/yum-repo:${VERSION} .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wisecloud/yum-repo:${VERSION}
